# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: playlist.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'playlist.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import user_pb2 as user__pb2
import song_pb2 as song__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eplaylist.proto\x12\x10playlist_package\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\nuser.proto\x1a\nsong.proto\"\x07\n\x05\x45mpty\"\x18\n\nPlaylistId\x12\n\n\x02id\x18\x01 \x01(\x05\"h\n\x08Playlist\x12\n\n\x02id\x18\x01 \x01(\x05\x12.\n\ncreated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04nome\x18\x03 \x01(\t\x12\x12\n\nusuario_id\x18\x04 \x01(\x05\"=\n\x0cPlaylistList\x12-\n\tplaylists\x18\x01 \x03(\x0b\x32\x1a.playlist_package.Playlist2\xf4\x01\n\x0fPlaylistService\x12G\n\x0bGetPlaylist\x12\x1c.playlist_package.PlaylistId\x1a\x1a.playlist_package.Playlist\x12J\n\x12GetPlaylistsByUser\x12\x14.user_package.UserId\x1a\x1e.playlist_package.PlaylistList\x12L\n\x14GetPlaylistsBySongId\x12\x14.song_package.SongId\x1a\x1e.playlist_package.PlaylistListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'playlist_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=93
  _globals['_EMPTY']._serialized_end=100
  _globals['_PLAYLISTID']._serialized_start=102
  _globals['_PLAYLISTID']._serialized_end=126
  _globals['_PLAYLIST']._serialized_start=128
  _globals['_PLAYLIST']._serialized_end=232
  _globals['_PLAYLISTLIST']._serialized_start=234
  _globals['_PLAYLISTLIST']._serialized_end=295
  _globals['_PLAYLISTSERVICE']._serialized_start=298
  _globals['_PLAYLISTSERVICE']._serialized_end=542
# @@protoc_insertion_point(module_scope)
