# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: song.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'song.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nsong.proto\x12\x0csong_package\x1a\x1fgoogle/protobuf/timestamp.proto\"\x07\n\x05\x45mpty\"\x14\n\x06SongId\x12\n\n\x02id\x18\x01 \x01(\x05\"\x18\n\nPlaylistId\x12\n\n\x02id\x18\x01 \x01(\x05\"a\n\x04Song\x12\n\n\x02id\x18\x01 \x01(\x05\x12.\n\ncreated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04nome\x18\x03 \x01(\t\x12\x0f\n\x07\x61rtista\x18\x04 \x01(\t\"-\n\x08SongList\x12!\n\x05songs\x18\x01 \x03(\x0b\x32\x12.song_package.Song2\xc6\x01\n\x0bSongService\x12\x39\n\nGetAllSong\x12\x13.song_package.Empty\x1a\x16.song_package.SongList\x12\x33\n\x07GetSong\x12\x14.song_package.SongId\x1a\x12.song_package.Song\x12G\n\x13GetSongByPlaylistId\x12\x18.song_package.PlaylistId\x1a\x16.song_package.SongListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'song_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=61
  _globals['_EMPTY']._serialized_end=68
  _globals['_SONGID']._serialized_start=70
  _globals['_SONGID']._serialized_end=90
  _globals['_PLAYLISTID']._serialized_start=92
  _globals['_PLAYLISTID']._serialized_end=116
  _globals['_SONG']._serialized_start=118
  _globals['_SONG']._serialized_end=215
  _globals['_SONGLIST']._serialized_start=217
  _globals['_SONGLIST']._serialized_end=262
  _globals['_SONGSERVICE']._serialized_start=265
  _globals['_SONGSERVICE']._serialized_end=463
# @@protoc_insertion_point(module_scope)
