# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import song_pb2 as song__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in song_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SongServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllSong = channel.unary_unary(
                '/song_package.SongService/GetAllSong',
                request_serializer=song__pb2.Empty.SerializeToString,
                response_deserializer=song__pb2.SongList.FromString,
                _registered_method=True)
        self.GetSong = channel.unary_unary(
                '/song_package.SongService/GetSong',
                request_serializer=song__pb2.SongId.SerializeToString,
                response_deserializer=song__pb2.Song.FromString,
                _registered_method=True)
        self.GetSongByPlaylistId = channel.unary_unary(
                '/song_package.SongService/GetSongByPlaylistId',
                request_serializer=song__pb2.PlaylistId.SerializeToString,
                response_deserializer=song__pb2.SongList.FromString,
                _registered_method=True)


class SongServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSongByPlaylistId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SongServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllSong': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllSong,
                    request_deserializer=song__pb2.Empty.FromString,
                    response_serializer=song__pb2.SongList.SerializeToString,
            ),
            'GetSong': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSong,
                    request_deserializer=song__pb2.SongId.FromString,
                    response_serializer=song__pb2.Song.SerializeToString,
            ),
            'GetSongByPlaylistId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSongByPlaylistId,
                    request_deserializer=song__pb2.PlaylistId.FromString,
                    response_serializer=song__pb2.SongList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'song_package.SongService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('song_package.SongService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SongService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/song_package.SongService/GetAllSong',
            song__pb2.Empty.SerializeToString,
            song__pb2.SongList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/song_package.SongService/GetSong',
            song__pb2.SongId.SerializeToString,
            song__pb2.Song.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSongByPlaylistId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/song_package.SongService/GetSongByPlaylistId',
            song__pb2.PlaylistId.SerializeToString,
            song__pb2.SongList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
