DROP TABLE IF EXISTS public_test.musicas;

CREATE TABLE IF NOT EXISTS public_test.musicas (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    nome TEXT,
    artista TEXT
);

INSERT INTO public_test.musicas (nome, artista)
VALUES
    ('Blinding Lights', 'The Weeknd'),
    ('Watermelon Sugar', 'Harry Styles'),
    ('Shape of You', 'Ed Sheeran'),
    ('Uptown Funk', 'Mark Ronson ft. Bruno Mars'),
    ('Levitating', 'Dua Lipa'),
    ('Bad Guy', 'Billie Eilish'),
    ('Someone Like You', 'Adele'),
    ('Rolling in the Deep', 'Adele'),
    ('Yesterday', 'The Beatles'),
    ('Hey Jude', 'The Beatles'),
    ('Billie Jean', 'Michael Jackson'),
    ('Smooth Criminal', 'Michael Jackson'),
    ('Smells Like Teen Spirit', 'Nirvana'),
    ('Come As You Are', 'Nirvana'),
    ('Lose Yourself', 'Eminem'),
    ('Without Me', 'Eminem'),
    ('Bohemian Rhapsody', 'Queen'),
    ('Don''t Stop Me Now', 'Queen'),
    ('Hotel California', 'Eagles'),
    ('Take It Easy', 'Eagles'),
    ('Wonderwall', 'Oasis'),
    ('Champagne Supernova', 'Oasis'),
    ('Viva La Vida', 'Coldplay'),
    ('Fix You', 'Coldplay'),
    ('Numb', 'Linkin Park'),
    ('In the End', 'Linkin Park'),
    ('Humble', 'Kendrick Lamar'),
    ('Alright', 'Kendrick Lamar'),
    ('Starboy', 'The Weeknd'),
    ('Peaches', 'Justin Bieber'),
    ('Sorry', 'Justin Bieber'),
    ('Shake It Off', 'Taylor Swift'),
    ('Blank Space', 'Taylor Swift'),
    ('Anti-Hero', 'Taylor Swift'),
    ('Unholy', 'Sam Smith'),
    ('Stay', 'The Kid LAROI & Justin Bieber'),
    ('Shallow', 'Lady Gaga & Bradley Cooper'),
    ('Poker Face', 'Lady Gaga'),
    ('Royals', 'Lorde'),
    ('Team', 'Lorde'),
    ('Take On Me', 'A-ha'),
    ('Africa', 'Toto'),
    ('Beat It', 'Michael Jackson'),
    ('Thriller', 'Michael Jackson'),
    ('Toxic', 'Britney Spears'),
    ('...Baby One More Time', 'Britney Spears'),
    ('Hips Don''t Lie', 'Shakira'),
    ('Waka Waka', 'Shakira'),
    ('Despacito', 'Luis Fonsi & Daddy Yankee'),
    ('Gasolina', 'Daddy Yankee'),
    ('Mi Gente', 'J Balvin'),
    ('Dákiti', 'Bad Bunny'),
    ('Tití Me Preguntó', 'Bad Bunny'),
    ('Hello', 'Adele'),
    ('Set Fire to the Rain', 'Adele'),
    ('All of Me', 'John Legend'),
    ('Thinking Out Loud', 'Ed Sheeran'),
    ('Perfect', 'Ed Sheeran'),
    ('Sunflower', 'Post Malone'),
    ('Circles', 'Post Malone'),
    ('Rockstar', 'Post Malone'),
    ('Radioactive', 'Imagine Dragons'),
    ('Believer', 'Imagine Dragons'),
    ('Demons', 'Imagine Dragons'),
    ('Bad Habits', 'Ed Sheeran'),
    ('As It Was', 'Harry Styles'),
    ('Golden', 'Harry Styles'),
    ('Halo', 'Beyoncé'),
    ('Single Ladies', 'Beyoncé'),
    ('Umbrella', 'Rihanna'),
    ('Diamonds', 'Rihanna'),
    ('Stay', 'Rihanna'),
    ('Stronger', 'Kanye West'),
    ('Heartless', 'Kanye West'),
    ('Vogue', 'Madonna'),
    ('Like a Prayer', 'Madonna'),
    ('Juice', 'Lizzo'),
    ('Truth Hurts', 'Lizzo'),
    ('Drivers License', 'Olivia Rodrigo'),
    ('Good 4 U', 'Olivia Rodrigo'),
    ('Deja Vu', 'Olivia Rodrigo'),
    ('God''s Plan', 'Drake'),
    ('One Dance', 'Drake'),
    ('Hotline Bling', 'Drake'),
    ('Seven Nation Army', 'The White Stripes'),
    ('Fell in Love With a Girl', 'The White Stripes'),
    ('Creep', 'Radiohead'),
    ('Karma Police', 'Radiohead'),
    ('Zombie', 'The Cranberries'),
    ('Dreams', 'The Cranberries'),
    ('Mr. Brightside', 'The Killers'),
    ('Somebody Told Me', 'The Killers'),
    ('Take Me to Church', 'Hozier'),
    ('Work', 'Rihanna ft. Drake');
