DROP TABLE IF EXISTS public_test.playlists CASCADE;

CREATE TABLE public_test.playlists
(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    nome TEXT
);

INSERT INTO public_test.playlists (nome)
SELECT * FROM (
    VALUES
    ('songs for when i can’t focus'),
    ('old stuff but good'),
    ('chill vibes only 🌙'),
    ('for the bus ride'),
    ('mom''s favorites lol'),
    ('study?? maybe'),
    ('late night thoughts'),
    ('random mix 01'),
    ('random mix 02'),
    ('random mix 03'),
    ('car jams 🚗💨'),
    ('playlist i keep renaming'),
    ('the good stuff™'),
    ('songs i found on tiktok'),
    ('train home kind of mood'),
    ('sunday cleaning playlist'),
    ('work but not too serious'),
    ('work but serious'),
    ('gym but gentle'),
    ('I swear this makes sense'),
    ('why do i have so many playlists'),
    ('AAAAAAAAAAAAAA'),
    ('the classics (my classics)'),
    ('vibes??'),
    ('my 2020 crisis playlist'),
    ('songs i lied about knowing'),
    ('im fine :)'),
    ('songs to pretend im in a movie'),
    ('rainy day good feels'),
    ('stuff from childhood'),
    ('stuff from college'),
    ('stuff from yesterday lol'),
    ('my favs but only sometimes'),
    ('nightdrive but i cant drive'),
    ('happy-ish'),
    ('sad but aesthetic'),
    ('focus but not boring'),
    ('the ONE playlist to rule them all'),
    ('cooking w/ pasta sauce playlist'),
    ('don’t judge me'),
    ('IF YOU KNOW YOU KNOW'),
    ('idk man'),
    ('ok this one is actually good'),
    ('for walking fast as hell'),
    ('songs for scrolling'),
    ('songs that hurt but in a good way'),
    ('👁️👄👁️'),
    ('my comfort playlist'),
    ('songs for february'),
    ('songs for april'),
    ('songs for no specific reason'),
    ('my gf hates this playlist'),
    ('songs i pretend i discovered'),
    ('vibes but chaotic'),
    ('chaos mode engaged'),
    ('help me concentrate pls'),
    ('i did NOT make this while drunk'),
    ('songs that make me go feral'),
    ('playlist for existential dread'),
    ('tiny serotonin boost'),
    ('very specific mood #1'),
    ('very specific mood #2'),
    ('songs that sound green'),
    ('songs that sound purple'),
    ('songs shaped like a triangle'),
    ('music for when im being dramatic'),
    ('music my cat likes'),
    ('coding at 3am'),
    ('coding at 3pm'),
    ('coding but crying'),
    ('playlist for avoiding responsibilities'),
    ('tidying my life up (again)'),
    ('✧ magical girl energy ✧'),
    ('villain arc starter pack'),
    ('hero arc starter pack'),
    ('bread-making vibes'),
    ('laundry day essentials'),
    ('songs i skipped but now love'),
    ('this playlist makes me feel tall'),
    ('i’m not okay (i am)'),
    ('LOFI BUT STRONG'),
    ('forest-core 🌲'),
    ('coffee shop rainy morning'),
    ('ye olde playlist'),
    ('playlist #27'),
    ('playlist #39 i think?'),
    ('playlist-final-v2-FINAL'),
    ('god pls help this playlist'),
    ('ok hear me out'),
    ('songs my ex hated (lol)'),
    ('songs my ex loved (ugh)'),
    ('movie soundtrack *if i directed the movie*'),
    ('girlboss mode activated'),
    ('BOYBOSS MODE????'),
    ('music to speedrun chores'),
    ('walking like the main character'),
    ('songs i want at my wedding'),
    ('songs NOT allowed at my wedding'),
    ('songs that feel like clouds'),
    ('songs that feel like fire'),
    ('songs that feel like citrus idk'),
    ('brain go brrrr'),
    ('✨ pretty sounds ✨'),
    ('aggressively positive playlist'),
    ('aggressively negative playlist'),
    ('songs for scrolling my life away'),
    ('songs for going outside (rare)'),
    ('for when im pretending to study'),
    ('stuff i found at 2am'),
    ('stuff i found at 5am'),
    ('why is this actually good'),
    ('stuff to play when friends come over'),
    ('songs for avoiding everyone'),
    ('baby''s first playlist'),
    ('what even IS this'),
    ('my neighbor hates this list'),
    ('energy!!!'),
    ('super chill super calm'),
    ('playlist with zero skips (for me)'),
    ('chaotic energy 🔥'),
    ('songs to hum in the shower'),
    ('songs for staring at the ceiling'),
    ('playlist that fixes my brain'),
    ('playlist that breaks my brain'),
    ('audio comfort food'),
    ('music for walking like u have a purpose'),
    ('music for walking like u DONT'),
    ('i’ll delete this later (never)'),
    ('don’t play this at work'),
    ('songs i want to forget then rediscover'),
    ('idk how to name playlists'),
    ('max concentration mode'),
    ('minimal brain activity playlist'),
    ('deep focus but cozy'),
    ('I DID MY BEST OK'),
    ('songs that make me want to travel'),
    ('songs that make me want to clean'),
    ('songs that make me want to cry a bit'),
    ('happy little playlist'),
    ('sad little playlist'),
    ('angry little playlist'),
    ('my entire personality rn'),
    ('bops'),
    ('super mega bops'),
    ('songs to levitate to'),
    ('songs to teleport to'),
    ('🧃 juice vibes'),
    ('🌧️ rain brain'),
    ('✨ soft girl hour ✨'),
    ('🌞 sunny pensive vibe'),
    ('👉👈 pls listen gently'),
    ('music to pretend im okay to'),
    ('songs with ✨that vibe✨'),
    ('songs from people with questionable opinions'),
    ('WHAT IS A GENRE ANYWAY'),
    ('the “im bored” playlist'),
    ('house chores but epic'),
    ('i should be sleeping'),
    ('this playlist is taller than me'),
    ('my phone suggested this name??'),
    ('sleepy slow soft'),
    ('ENERGY DRINK FOR EARS'),
    ('songs for walking home in rain'),
    ('songs for existential shower'),
    ('music to edit photos to'),
    ('i made this on accident'),
    ('this should not work but it does'),
    ('songs to play during mario kart'),
    ('slowly losing my mind mix'),
    ('this one slaps trust me'),
    ('i swear there is a theme here'),
    ('music for staring out of a car window'),
    ('calm storm'),
    ('chaotic calmness'),
    ('?? just music ??'),
    ('ok but hear me out 2'),
    ('i finally cleaned my room playlist'),
    ('music for pretending to work'),
    ('songs my dad likes for some reason'),
    ('songs that feel like soup'),
    ('my “good taste” playlist'),
    ('my “bad taste” playlist'),
    ('my 2014 era playlist'),
    ('nostalgia but slightly cursed'),
    ('retrowave roadtrip'),
    ('if i was in an indie movie'),
    ('songs i wish i heard sooner'),
    ('songs i forgot existed'),
    ('late night anxiety be gone'),
    ('songs that smell like vanilla'),
    ('songs that smell like rain'),
    ('songs that smell like asphalt'),
    ('walking like i have secrets'),
    ('stuff to play while cooking rice'),
    ('the ✨vibe✨ is immaculate'),
    ('vibe check passed'),
    ('vibe check FAILED'),
    ('music to panic calmly to'),
    ('music to panic LOUDLY to'),
    ('songs for dreaming awake'),
    ('songs for dramatic exits'),
    ('coffee + headphones playlist'),
    ('songs that feel yellow'),
    ('songs that feel blue'),
    ('sleep but not too fast'),
    ('i should name this later'),
    ('playlist for being productive-ish'),
    ('songs with cool bass lines'),
    ('soft chaotic energy'),
    ('music for when reality is optional'),
    ('productive panic'),
    ('i forgot why i made this'),
    ('this playlist has lore'),
    ('weirdly specific feelings'),
    ('good for commutes idk'),
    ('midnight wanderer'),
    ('songs for people who overthink'),
    ('songs for people who underthink'),
    ('brain.exe stopped working'),
    ('why are all songs about feelings'),
    ('not me making another playlist'),
    ('my 2am playlist'),
    ('my 4pm playlist'),
    ('i blame spotify'),
    ('feels like floating'),
    ('feels like sinking'),
    ('feels like both'),
    ('songs to quietly scream to'),
    ('fake confidence playlist'),
    ('hero soundtrack (me)'),
    ('villain soundtrack (also me)'),
    ('mood: potato'),
    ('mood: dragon'),
    ('mood: LOL IDK'),
    ('soft playlist for hard days'),
    ('hard playlist for soft days'),
    ('my comfort songs 2'),
    ('my comfort songs 3'),
    ('this playlist is haunted'),
    ('this playlist is blessed'),
    ('songs with ✨good vibes✨'),
    ('songs with weird vibes but good'),
    ('songs that could fix the world'),
    ('songs that could destroy the world'),
    ('music for pretending i have my life together'),
    ('music for accepting that i don’t'))
LIMIT 200;