DROP TABLE IF EXISTS public_test.usuarios CASCADE;

CREATE TABLE public_test.usuarios (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    nome TEXT,
    idade SMALLINT
);

INSERT INTO public_test.usuarios (nome, idade)
    VALUES
        ('Lucas Ferreira', 19),
        ('Marina Costa', 20),
        ('João Pedro Almeida', 21),
        ('Ana Júlia Martins', 22),
        ('Felipe Moreira', 23),
        ('Camila Rocha', 24),
        ('Rafael Azevedo', 25),
        ('Bruna Oliveira', 26),
        ('Pedro Henrique Ramos', 27),
        ('Vitória Santos', 28),
        ('Isabela Pereira', 29),
        ('Gustavo Carvalho', 30),
        ('Daniela Correia', 31),
        ('Thiago Duarte', 32),
        ('Letícia Ramos', 33),
        ('Nicolas Pinto', 34),
        ('Clara Vieira', 35),
        ('Eduardo Farias', 36),
        ('Beatriz Fonseca', 37),
        ('Henrique Barros', 38),
        ('Larissa Lima', 39),
        ('André Silveira', 40),
        ('Júlia Nogueira', 41),
        ('Mateus Dias', 42),
        ('Patrícia Alves', 43),
        ('Diego Fernandes', 44),
        ('Aline Cardoso', 45),
        ('Rodrigo Braga', 46),
        ('Carolina Neves', 47),
        ('Fernando Rezende', 48),
        ('Luiza Gomes', 49),
        ('Marcelo Ribeiro', 50),
        ('Helena Prado', 51),
        ('Alexandre Tavares', 52),
        ('Renata Castro', 53),
        ('Leonardo Moura', 54),
        ('Sofia Barros', 55),
        ('Bruno Torres', 56),
        ('Gabriela Rezende', 57),
        ('Paulo Ricardo', 18),
        ('Mário J. Couto', 19),
        ('Anny Felps', 20),
        ('Ricardo “Rick” Moraes', 21),
        ('Sabrina Costa', 22),
        ('Lívia Andrade', 23),
        ('Tomás Veloso', 24),
        ('Caio Vilar', 25),
        ('Bia Mendes', 26),
        ('José Luiz', 27),
        ('Mariza N.', 28),
        ('Carol P.', 29),
        ('Vinícius “Vini” Amaral', 30),
        ('Guilherme Antunes', 31),
        ('Nathália F.', 32),
        ('João “JP” Pacheco', 33),
        ('Eduarda Moraes', 34),
        ('Lorenzo Bittencourt', 35),
        ('Mirela Castilho', 36),
        ('Anderson da Luz', 37),
        ('Roberta V.', 38),
        ('Amanda Soares', 39),
        ('Emanuel S.', 40),
        ('Cíntia de Paula', 41),
        ('Danilo B.', 42),
        ('Jéssica Reis', 43),
        ('Vagner L.', 44),
        ('Carla Moretti', 45),
        ('Renan Prado', 46),
        ('Debora F.', 47),
        ('Samuel Rocha', 48),
        ('Vanessa Lima', 49),
        ('Igor Martins', 50),
        ('Mayara Lopes', 51),
        ('Otávio C.', 52),
        ('Yasmin Duarte', 53),
        ('Fábio Teles', 54),
        ('Pâmela Cristine', 55),
        ('Gabriel “Gabs” Mota', 56),
        ('Luana Pires', 57),
        ('Ruan Diego', 18),
        ('Letícyah (typo)', 19),
        ('Hugo R.', 20),
        ('Milena Solano', 21),
        ('Victor F.', 22),
        ('Thaís G.', 23),
        ('Rafaela Dias', 24),
        ('Sérgio N.', 25),
        ('Priscila S.', 26),
        ('Caue “Cauê” Silva', 27),
        ('Elaine Moraes', 28),
        ('Kauã M.', 29),
        ('Lilian Torres', 30),
        ('Albert Mendonça', 31),
        ('Daniela F.', 32),
        ('João Carlos', 33),
        ('Ana Flávia', 34),
        ('Pietro Andrade', 35),
        ('Eloá M.', 36),
        ('César F.', 37),
        ('Denise A.', 38),
        ('Emma Johnson', 39),
        ('Liam Carter', 40),
        ('Chloe Wilson', 41),
        ('Noah Mitchell', 42),
        ('Emily Rogers', 43),
        ('Aiden Cooper', 44),
        ('Mia Turner', 45),
        ('Ethan Martin', 46),
        ('Ava Thompson', 47),
        ('James Baker', 48),
        ('Naomi Clarke', 49),
        ('Hiro Tanaka', 50),
        ('Sora Watanabe', 51),
        ('Akira Fujimoto', 52),
        ('Yuri Nakamura', 53),
        ('Miguel Hernández', 54),
        ('Sofía Gómez', 55),
        ('Álvaro Ruiz', 56),
        ('Lucía Fernández', 57),
        ('Diego Ramírez', 18),
        ('maria clara', 19),
        ('julio cesr (typo)', 20),
        ('pedro_lima98', 21),
        ('Ana--Beatriz', 22),
        ('R@fa Moreira', 23),
        ('Jonatas', 24),
        ('Kelvyn', 25),
        ('Joao V. Neto', 26),
        ('Paola S2', 27),
        ('Líllian (double L)', 28),
        ('Téo Batista', 29),
        ('Heloisa Martins', 30),
        ('Marcos Vinícius', 31),
        ('Ana C. Prado', 32),
        ('Kauan Ribeiro', 33),
        ('Murilo Andrade', 34),
        ('Davi Luiz', 35),
        ('Sthefany Rocha', 36),
        ('Otto Vieira', 37),
        ('Joice Ferreira', 38),
        ('Ester Maia', 39),
        ('Heitor Silveira', 40),
        ('Lara P.', 41),
        ('Nathan Souza', 42),
        ('Ayla Nascimento', 43),
        ('Samuel K.', 44),
        ('Melissa Duarte', 45),
        ('Bryan Torres', 46),
        ('Joana Peçanha', 47),
        ('Caetano Bragança', 48),
        ('Valentina S.', 49),
        ('Arthur Lisboa', 50),
        ('Giovanna Meireles', 51),
        ('Kevin Santos', 52),
        ('Catarina Galvão', 53),
        ('André Luiz', 54),
        ('Elaíne (accent typo)', 55),
        ('Raul C.', 56),
        ('Betina Castro', 57),
        ('Yago Vieira', 18),
        ('Pollyanna (weird name)', 19),
        ('Rulian (typo)', 20),
        ('Tayná', 21),
        ('Icaro', 22),
        ('Maiane', 23),
        ('Gerson Alves', 24),
        ('Claudia Luz', 25),
        ('Eugênio S.', 26),
        ('Luma F.', 27),
        ('Otília Santos', 28),
        ('Zion Pereira', 29),
        ('Gael Magalhães', 30),
        ('Jhonatan (common typo)', 31),
        ('Kelvin Morais', 32),
        ('Malu Rios', 33),
        ('João Artur', 34),
        ('Vitória Anne', 35),
        ('Ítalo Santos', 36),
        ('Gabriele S.', 37),
        ('Loren H.', 38),
        ('Afonso Braga', 39),
        ('Nina Castro', 40),
        ('Theo Porto', 41),
        ('Ellie Marques', 42),
        ('Dan C.', 43),
        ('Isis P.', 44),
        ('Ryan A.', 45),
        ('Manuela A.', 46),
        ('Vinicius D.', 47),
        ('Paulo S.', 48),
        ('Joaoo (typo)', 49),
        ('Sara Monteiro', 50),
        ('Marcela Ramos', 51),
        ('Brendon V.', 52),
        ('José Neto', 53),
        ('Nicolly (popular alt spelling)', 54),
        ('Derick Silva', 55),
        ('Evelyn Costa', 56),
        ('Caio César', 57),
        ('Mari Palma', 18);
